services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: linkFolio
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      
